blastn_parameters :
  dbpath_nt : /path/to/nt/nt
  nb_threads_bn : 28
  evalue_nt : 0.01

filter_blastn_parameters :
 d : 10
 l : 50
 I : 1

blastx_parameters :
  dbpath_vrl : /path/to/virnr/viruses_nr_prots.100p.faa
  dbpath_nr : /path/to/nr/nr
  nb_threads_bx : 28
  evalue_vir : 0.1
  evalue_nr : 0.01

filter_blastx_parameters :
  d : 10
  l : 17
  I : 1

add_taxo_parameters :
  tax_lineages_file : /home/path/to/fullnamelineage_taxid_sorted.dmp

blast_path : /path/to/ncbi-blast-2.12.0+/bin
